name: Docker
on:
  schedule:
    - cron: '24 */6 * * *'
  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into registry docker.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get bashbrew
        run: curl -fsSL https://doi-janky.infosiftr.net/job/bashbrew/job/master/lastSuccessfulBuild/artifact/bashbrew-amd64 -o ../bashbrew && chmod +x ../bashbrew

      - name: Clone docker official images repo
        run: git clone --depth=1 https://github.com/docker-library/official-images ../docker-official-images

      - name: Run build
        run: ./build ../docker-official-images

      #- name: Extract Docker metadata from docker.io
      #  id: docker-io-meta
      #  uses: docker/metadata-action@v3
      #  with:
      #    images: docker.io/_/nextcloud
          #labels: |
          #  org.opencontainers.image.url=https://github.com/Hellyna/docker-nextcloud
          #  org.opencontainers.image.source=https://github.com/Hellyna/docker-nextcloud

      #- name: Build and push Docker image to ghcr.io
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: .
      #    push: ${{ github.event_name != 'pull_request' }}
      #    tags: ${{ steps.ghcr-io-meta.outputs.tags }}
      #    labels: ${{ steps.ghcr-io-meta.outputs.labels }}

      #- name: Build and push Docker image to docker.io
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: .
      #    push: ${{ github.event_name != 'pull_request' }}
      #    tags: ${{ steps.docker-io-meta.outputs.tags }}
      #    labels: ${{ steps.docker-io-meta.outputs.labels }}
